from app import db
from app.models import User, Course
import datetime


def reset_db():
    db.drop_all()
    db.create_all()

    users =[
        {'username': 'amy',   'email': 'amy@b.com', 'role': 'Admin', 'pw': 'amy.pw'},
        {'username': 'tom',   'email': 'tom@b.com',                  'pw': 'amy.pw'},
        {'username': 'yin',   'email': 'yin@b.com', 'role': 'Admin', 'pw': 'amy.pw'},
        {'username': 'tariq', 'email': 'trq@b.com',                  'pw': 'amy.pw'},
        {'username': 'jo',    'email': 'jo@b.com',                   'pw': 'amy.pw'}
    ]

    # adding users to the session:
    for u in users:
        # get the password value and remove it from the dict:
        pw = u.pop('pw')
        # create a new user object using the parameters defined by the remaining entries in the dict:
        user = User(**u)
        # set the password for the user object:
        user.set_password(pw)
        # add the newly created user object to the database session:
        db.session.add(user)
    db.session.commit()

    # courses = [
    #     {"id": 1, "title": "Introduction to Blockchain 1", "platform": "edX", "difficulty": "Intermediate", "subject": "Blockchain", "url": "https://www.edx.org/course/introduction-to-blockchain-1"},
    #     {"id": 2, "title": "Introduction to Cybersecurity 2", "platform": "Udemy", "difficulty": "Intermediate", "subject": "Cybersecurity", "url": "https://www.udemy.com/course/introduction-to-cybersecurity-2"},
    #     {"id": 3, "title": "Introduction to Mobile Development 3", "platform": "LinkedIn Learning", "difficulty": "Intermediate", "subject": "Mobile Development", "url": "https://www.linkedin.com/learning/introduction-to-mobile-development-3"},
    #     {"id": 4, "title": "Introduction to Mobile Development 4", "platform": "edX", "difficulty": "Intermediate", "subject": "Mobile Development", "url": "https://www.edx.org/course/introduction-to-mobile-development-4"},
    #     {"id": 5, "title": "Introduction to Cybersecurity 5", "platform": "edX", "difficulty": "Advanced", "subject": "Cybersecurity", "url": "https://www.edx.org/course/introduction-to-cybersecurity-5"},
    #     {"id": 6, "title": "Introduction to AI 6", "platform": "edX", "difficulty": "Beginner", "subject": "AI", "url": "https://www.edx.org/course/introduction-to-ai-6"},
    #     {"id": 7, "title": "Introduction to Mobile Development 7", "platform": "Coursera", "difficulty": "Advanced", "subject": "Mobile Development", "url": "https://www.coursera.org/learn/introduction-to-mobile-development-7"},
    #     {"id": 8, "title": "Introduction to Cloud Computing 8", "platform": "Udemy", "difficulty": "Intermediate", "subject": "Cloud Computing", "url": "https://www.udemy.com/course/introduction-to-cloud-computing-8"},
    #     {"id": 9, "title": "Introduction to Cybersecurity 9", "platform": "Coursera", "difficulty": "Beginner", "subject": "Cybersecurity", "url": "https://www.coursera.org/learn/introduction-to-cybersecurity-9"},
    #     {"id": 10, "title": "Introduction to Cloud Computing 10", "platform": "LinkedIn Learning", "difficulty": "Beginner", "subject": "Cloud Computing", "url": "https://www.linkedin.com/learning/introduction-to-cloud-computing-10"},
    #     {"id": 11, "title": "Introduction to Natural Language Processing 11", "platform": "OpenLearn", "difficulty": "Intermediate", "subject": "Natural Language Processing", "url": "https://www.open.edu/openlearn/introduction-to-natural-language-processing-11"},
    #     {"id": 12, "title": "Introduction to Data Science 12", "platform": "Coursera", "difficulty": "Advanced", "subject": "Data Science", "url": "https://www.coursera.org/learn/introduction-to-data-science-12"},
    #     {"id": 13, "title": "Introduction to ML 13", "platform": "LinkedIn Learning", "difficulty": "Advanced", "subject": "ML", "url": "https://www.linkedin.com/learning/introduction-to-ml-13"},
    #     {"id": 14, "title": "Introduction to ML 14", "platform": "Udemy", "difficulty": "Advanced", "subject": "ML", "url": "https://www.udemy.com/course/introduction-to-ml-14"},
    #     {"id": 15, "title": "Introduction to AI 15", "platform": "FutureLearn", "difficulty": "Beginner", "subject": "AI", "url": "https://www.futurelearn.com/courses/introduction-to-ai-15"},
    #     {"id": 16, "title": "Introduction to Blockchain 16", "platform": "edX", "difficulty": "Advanced", "subject": "Blockchain", "url": "https://www.edx.org/course/introduction-to-blockchain-16"},
    #     {"id": 17, "title": "Introduction to Natural Language Processing 17", "platform": "LinkedIn Learning", "difficulty": "Intermediate", "subject": "Natural Language Processing", "url": "https://www.linkedin.com/learning/introduction-to-natural-language-processing-17"},
    #     {"id": 18, "title": "Introduction to Mobile Development 18", "platform": "OpenLearn", "difficulty": "Beginner", "subject": "Mobile Development", "url": "https://www.open.edu/openlearn/introduction-to-mobile-development-18"},
    #     {"id": 19, "title": "Introduction to Cloud Computing 19", "platform": "FutureLearn", "difficulty": "Intermediate", "subject": "Cloud Computing", "url": "https://www.futurelearn.com/courses/introduction-to-cloud-computing-19"},
    #     {"id": 20, "title": "Introduction to Data Science 20", "platform": "FutureLearn", "difficulty": "Beginner", "subject": "Data Science", "url": "https://www.futurelearn.com/courses/introduction-to-data-science-20"},
    #     {"id": 21, "title": "Introduction to Web Development 21", "platform": "OpenLearn", "difficulty": "Beginner",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-21"},
    #     {"id": 22, "title": "Introduction to Blockchain 22", "platform": "LinkedIn Learning", "difficulty": "Advanced",
    #      "subject": "Blockchain", "url": "https://www.linkedin.com/learning/introduction-to-blockchain-22"},
    #     {"id": 23, "title": "Introduction to Cloud Computing 23", "platform": "Coursera", "difficulty": "Intermediate",
    #      "subject": "Cloud Computing", "url": "https://www.coursera.org/learn/introduction-to-cloud-computing-23"},
    #     {"id": 24, "title": "Introduction to Cloud Computing 24", "platform": "Coursera", "difficulty": "Beginner",
    #      "subject": "Cloud Computing", "url": "https://www.coursera.org/learn/introduction-to-cloud-computing-24"},
    #     {"id": 25, "title": "Introduction to Computer Vision 25", "platform": "Udemy", "difficulty": "Intermediate",
    #      "subject": "Computer Vision", "url": "https://www.udemy.com/course/introduction-to-computer-vision-25"},
    #     {"id": 26, "title": "Introduction to Cybersecurity 26", "platform": "LinkedIn Learning",
    #      "difficulty": "Beginner", "subject": "Cybersecurity",
    #      "url": "https://www.linkedin.com/learning/introduction-to-cybersecurity-26"},
    #     {"id": 27, "title": "Introduction to Cybersecurity 27", "platform": "edX", "difficulty": "Advanced",
    #      "subject": "Cybersecurity", "url": "https://www.edx.org/course/introduction-to-cybersecurity-27"},
    #     {"id": 28, "title": "Introduction to AI 28", "platform": "edX", "difficulty": "Advanced", "subject": "AI",
    #      "url": "https://www.edx.org/course/introduction-to-ai-28"},
    #     {"id": 29, "title": "Introduction to AI 29", "platform": "Coursera", "difficulty": "Intermediate",
    #      "subject": "AI", "url": "https://www.coursera.org/learn/introduction-to-ai-29"},
    #     {"id": 30, "title": "Introduction to Mobile Development 30", "platform": "OpenLearn",
    #      "difficulty": "Intermediate", "subject": "Mobile Development",
    #      "url": "https://www.open.edu/openlearn/introduction-to-mobile-development-30"},
    #     {"id": 31, "title": "Introduction to Cloud Computing 31", "platform": "edX", "difficulty": "Beginner",
    #      "subject": "Cloud Computing", "url": "https://www.edx.org/course/introduction-to-cloud-computing-31"},
    #     {"id": 32, "title": "Introduction to AI 32", "platform": "LinkedIn Learning", "difficulty": "Advanced",
    #      "subject": "AI", "url": "https://www.linkedin.com/learning/introduction-to-ai-32"},
    #     {"id": 33, "title": "Introduction to Mobile Development 33", "platform": "FutureLearn",
    #      "difficulty": "Beginner", "subject": "Mobile Development",
    #      "url": "https://www.futurelearn.com/courses/introduction-to-mobile-development-33"},
    #     {"id": 34, "title": "Introduction to Web Development 34", "platform": "OpenLearn", "difficulty": "Advanced",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-34"},
    #     {"id": 35, "title": "Introduction to Web Development 35", "platform": "OpenLearn", "difficulty": "Intermediate",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-35"},
    #     {"id": 36, "title": "Introduction to Data Science 36", "platform": "edX", "difficulty": "Intermediate",
    #      "subject": "Data Science", "url": "https://www.edx.org/course/introduction-to-data-science-36"},
    #     {"id": 37, "title": "Introduction to Computer Vision 37", "platform": "LinkedIn Learning",
    #      "difficulty": "Beginner", "subject": "Computer Vision",
    #      "url": "https://www.linkedin.com/learning/introduction-to-computer-vision-37"},
    #     {"id": 38, "title": "Introduction to Mobile Development 38", "platform": "Coursera", "difficulty": "Advanced",
    #      "subject": "Mobile Development",
    #      "url": "https://www.coursera.org/learn/introduction-to-mobile-development-38"},
    #     {"id": 39, "title": "Introduction to Web Development 39", "platform": "LinkedIn Learning",
    #      "difficulty": "Intermediate", "subject": "Web Development",
    #      "url": "https://www.linkedin.com/learning/introduction-to-web-development-39"},
    #     {"id": 40, "title": "Introduction to Web Development 40", "platform": "Coursera", "difficulty": "Intermediate",
    #      "subject": "Web Development", "url": "https://www.coursera.org/learn/introduction-to-web-development-40"},
    #     {"id": 41, "title": "Introduction to Computer Vision 41", "platform": "Udemy", "difficulty": "Intermediate",
    #      "subject": "Computer Vision", "url": "https://www.udemy.com/course/introduction-to-computer-vision-41"},
    #     {"id": 42, "title": "Introduction to Natural Language Processing 42", "platform": "LinkedIn Learning",
    #      "difficulty": "Beginner", "subject": "Natural Language Processing",
    #      "url": "https://www.linkedin.com/learning/introduction-to-natural-language-processing-42"},
    #     {"id": 43, "title": "Introduction to Cloud Computing 43", "platform": "edX", "difficulty": "Intermediate",
    #      "subject": "Cloud Computing", "url": "https://www.edx.org/course/introduction-to-cloud-computing-43"},
    #     {"id": 44, "title": "Introduction to Natural Language Processing 44", "platform": "Udemy",
    #      "difficulty": "Advanced", "subject": "Natural Language Processing",
    #      "url": "https://www.udemy.com/course/introduction-to-natural-language-processing-44"},
    #     {"id": 45, "title": "Introduction to Cybersecurity 45", "platform": "edX", "difficulty": "Beginner",
    #      "subject": "Cybersecurity", "url": "https://www.edx.org/course/introduction-to-cybersecurity-45"},
    #     {"id": 46, "title": "Introduction to Natural Language Processing 46", "platform": "OpenLearn",
    #      "difficulty": "Intermediate", "subject": "Natural Language Processing",
    #      "url": "https://www.open.edu/openlearn/introduction-to-natural-language-processing-46"},
    #     {"id": 47, "title": "Introduction to Cloud Computing 47", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "Cloud Computing", "url": "https://www.futurelearn.com/courses/introduction-to-cloud-computing-47"},
    #     {"id": 48, "title": "Introduction to Cybersecurity 48", "platform": "Coursera", "difficulty": "Beginner",
    #      "subject": "Cybersecurity", "url": "https://www.coursera.org/learn/introduction-to-cybersecurity-48"},
    #     {"id": 49, "title": "Introduction to Blockchain 49", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "Blockchain", "url": "https://www.futurelearn.com/courses/introduction-to-blockchain-49"},
    #     {"id": 50, "title": "Introduction to Cloud Computing 50", "platform": "LinkedIn Learning",
    #      "difficulty": "Beginner", "subject": "Cloud Computing",
    #      "url": "https://www.linkedin.com/learning/introduction-to-cloud-computing-50"},
    #     {"id": 51, "title": "Introduction to Computer Vision 51", "platform": "edX", "difficulty": "Advanced",
    #      "subject": "Computer Vision", "url": "https://www.edx.org/course/introduction-to-computer-vision-51"},
    #     {"id": 52, "title": "Introduction to Computer Vision 52", "platform": "edX", "difficulty": "Advanced",
    #      "subject": "Computer Vision", "url": "https://www.edx.org/course/introduction-to-computer-vision-52"},
    #     {"id": 53, "title": "Introduction to Web Development 53", "platform": "OpenLearn", "difficulty": "Beginner",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-53"},
    #     {"id": 54, "title": "Introduction to AI 54", "platform": "edX", "difficulty": "Advanced", "subject": "AI",
    #      "url": "https://www.edx.org/course/introduction-to-ai-54"},
    #     {"id": 55, "title": "Introduction to Cybersecurity 55", "platform": "edX", "difficulty": "Intermediate",
    #      "subject": "Cybersecurity", "url": "https://www.edx.org/course/introduction-to-cybersecurity-55"},
    #     {"id": 56, "title": "Introduction to Computer Vision 56", "platform": "Udemy", "difficulty": "Advanced",
    #      "subject": "Computer Vision", "url": "https://www.udemy.com/course/introduction-to-computer-vision-56"},
    #     {"id": 57, "title": "Introduction to ML 57", "platform": "LinkedIn Learning", "difficulty": "Intermediate",
    #      "subject": "ML", "url": "https://www.linkedin.com/learning/introduction-to-ml-57"},
    #     {"id": 58, "title": "Introduction to Cybersecurity 58", "platform": "OpenLearn", "difficulty": "Advanced",
    #      "subject": "Cybersecurity", "url": "https://www.open.edu/openlearn/introduction-to-cybersecurity-58"},
    #     {"id": 59, "title": "Introduction to AI 59", "platform": "edX", "difficulty": "Advanced", "subject": "AI",
    #      "url": "https://www.edx.org/course/introduction-to-ai-59"},
    #     {"id": 60, "title": "Introduction to Web Development 60", "platform": "OpenLearn", "difficulty": "Intermediate",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-60"},
    #     {"id": 61, "title": "Introduction to Cloud Computing 61", "platform": "OpenLearn", "difficulty": "Intermediate",
    #      "subject": "Cloud Computing", "url": "https://www.open.edu/openlearn/introduction-to-cloud-computing-61"},
    #     {"id": 62, "title": "Introduction to AI 62", "platform": "Coursera", "difficulty": "Advanced", "subject": "AI",
    #      "url": "https://www.coursera.org/learn/introduction-to-ai-62"},
    #     {"id": 63, "title": "Introduction to Natural Language Processing 63", "platform": "FutureLearn",
    #      "difficulty": "Intermediate", "subject": "Natural Language Processing",
    #      "url": "https://www.futurelearn.com/courses/introduction-to-natural-language-processing-63"},
    #     {"id": 64, "title": "Introduction to Cloud Computing 64", "platform": "edX", "difficulty": "Beginner",
    #      "subject": "Cloud Computing", "url": "https://www.edx.org/course/introduction-to-cloud-computing-64"},
    #     {"id": 65, "title": "Introduction to Web Development 65", "platform": "Coursera", "difficulty": "Advanced",
    #      "subject": "Web Development", "url": "https://www.coursera.org/learn/introduction-to-web-development-65"},
    #     {"id": 66, "title": "Introduction to Web Development 66", "platform": "Coursera", "difficulty": "Advanced",
    #      "subject": "Web Development", "url": "https://www.coursera.org/learn/introduction-to-web-development-66"},
    #     {"id": 67, "title": "Introduction to Blockchain 67", "platform": "Coursera", "difficulty": "Beginner",
    #      "subject": "Blockchain", "url": "https://www.coursera.org/learn/introduction-to-blockchain-67"},
    #     {"id": 68, "title": "Introduction to AI 68", "platform": "OpenLearn", "difficulty": "Beginner", "subject": "AI",
    #      "url": "https://www.open.edu/openlearn/introduction-to-ai-68"},
    #     {"id": 69, "title": "Introduction to Cybersecurity 69", "platform": "Coursera", "difficulty": "Advanced",
    #      "subject": "Cybersecurity", "url": "https://www.coursera.org/learn/introduction-to-cybersecurity-69"},
    #     {"id": 70, "title": "Introduction to Data Science 70", "platform": "OpenLearn", "difficulty": "Intermediate",
    #      "subject": "Data Science", "url": "https://www.open.edu/openlearn/introduction-to-data-science-70"},
    #     {"id": 71, "title": "Introduction to Cloud Computing 71", "platform": "Udemy", "difficulty": "Advanced",
    #      "subject": "Cloud Computing", "url": "https://www.udemy.com/course/introduction-to-cloud-computing-71"},
    #     {"id": 72, "title": "Introduction to AI 72", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "AI", "url": "https://www.futurelearn.com/courses/introduction-to-ai-72"},
    #     {"id": 73, "title": "Introduction to ML 73", "platform": "Coursera", "difficulty": "Advanced", "subject": "ML",
    #      "url": "https://www.coursera.org/learn/introduction-to-ml-73"},
    #     {"id": 74, "title": "Introduction to Cybersecurity 74", "platform": "Udemy", "difficulty": "Beginner",
    #      "subject": "Cybersecurity", "url": "https://www.udemy.com/course/introduction-to-cybersecurity-74"},
    #     {"id": 75, "title": "Introduction to ML 75", "platform": "edX", "difficulty": "Advanced", "subject": "ML",
    #      "url": "https://www.edx.org/course/introduction-to-ml-75"},
    #     {"id": 76, "title": "Introduction to Mobile Development 76", "platform": "Udemy", "difficulty": "Advanced",
    #      "subject": "Mobile Development", "url": "https://www.udemy.com/course/introduction-to-mobile-development-76"},
    #     {"id": 77, "title": "Introduction to ML 77", "platform": "LinkedIn Learning", "difficulty": "Intermediate",
    #      "subject": "ML", "url": "https://www.linkedin.com/learning/introduction-to-ml-77"},
    #     {"id": 78, "title": "Introduction to Computer Vision 78", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "Computer Vision", "url": "https://www.futurelearn.com/courses/introduction-to-computer-vision-78"},
    #     {"id": 79, "title": "Introduction to Web Development 79", "platform": "OpenLearn", "difficulty": "Intermediate",
    #      "subject": "Web Development", "url": "https://www.open.edu/openlearn/introduction-to-web-development-79"},
    #     {"id": 80, "title": "Introduction to Natural Language Processing 80", "platform": "Coursera",
    #      "difficulty": "Intermediate", "subject": "Natural Language Processing",
    #      "url": "https://www.coursera.org/learn/introduction-to-natural-language-processing-80"},
    #     {"id": 81, "title": "Introduction to Mobile Development 81", "platform": "LinkedIn Learning",
    #      "difficulty": "Beginner", "subject": "Mobile Development",
    #      "url": "https://www.linkedin.com/learning/introduction-to-mobile-development-81"},
    #     {"id": 82, "title": "Introduction to Blockchain 82", "platform": "FutureLearn", "difficulty": "Advanced",
    #      "subject": "Blockchain", "url": "https://www.futurelearn.com/courses/introduction-to-blockchain-82"},
    #     {"id": 83, "title": "Introduction to Cloud Computing 83", "platform": "FutureLearn", "difficulty": "Advanced",
    #      "subject": "Cloud Computing", "url": "https://www.futurelearn.com/courses/introduction-to-cloud-computing-83"},
    #     {"id": 84, "title": "Introduction to Mobile Development 84", "platform": "FutureLearn",
    #      "difficulty": "Advanced", "subject": "Mobile Development",
    #      "url": "https://www.futurelearn.com/courses/introduction-to-mobile-development-84"},
    #     {"id": 85, "title": "Introduction to Web Development 85", "platform": "Coursera", "difficulty": "Beginner",
    #      "subject": "Web Development", "url": "https://www.coursera.org/learn/introduction-to-web-development-85"},
    #     {"id": 86, "title": "Introduction to Mobile Development 86", "platform": "Coursera", "difficulty": "Advanced",
    #      "subject": "Mobile Development",
    #      "url": "https://www.coursera.org/learn/introduction-to-mobile-development-86"},
    #     {"id": 87, "title": "Introduction to Natural Language Processing 87", "platform": "Coursera",
    #      "difficulty": "Beginner", "subject": "Natural Language Processing",
    #      "url": "https://www.coursera.org/learn/introduction-to-natural-language-processing-87"},
    #     {"id": 88, "title": "Introduction to AI 88", "platform": "edX", "difficulty": "Beginner", "subject": "AI",
    #      "url": "https://www.edx.org/course/introduction-to-ai-88"},
    #     {"id": 89, "title": "Introduction to ML 89", "platform": "Coursera", "difficulty": "Advanced", "subject": "ML",
    #      "url": "https://www.coursera.org/learn/introduction-to-ml-89"},
    #     {"id": 90, "title": "Introduction to Web Development 90", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "Web Development", "url": "https://www.futurelearn.com/courses/introduction-to-web-development-90"},
    #     {"id": 91, "title": "Introduction to Web Development 91", "platform": "Coursera", "difficulty": "Intermediate",
    #      "subject": "Web Development", "url": "https://www.coursera.org/learn/introduction-to-web-development-91"},
    #     {"id": 92, "title": "Introduction to ML 92", "platform": "edX", "difficulty": "Intermediate", "subject": "ML",
    #      "url": "https://www.edx.org/course/introduction-to-ml-92"},
    #     {"id": 93, "title": "Introduction to Mobile Development 93", "platform": "Coursera", "difficulty": "Beginner",
    #      "subject": "Mobile Development",
    #      "url": "https://www.coursera.org/learn/introduction-to-mobile-development-93"},
    #     {"id": 94, "title": "Introduction to Cloud Computing 94", "platform": "LinkedIn Learning",
    #      "difficulty": "Advanced", "subject": "Cloud Computing",
    #      "url": "https://www.linkedin.com/learning/introduction-to-cloud-computing-94"},
    #     {"id": 95, "title": "Introduction to Cybersecurity 95", "platform": "edX", "difficulty": "Advanced",
    #      "subject": "Cybersecurity", "url": "https://www.edx.org/course/introduction-to-cybersecurity-95"},
    #     {"id": 96, "title": "Introduction to Web Development 96", "platform": "FutureLearn", "difficulty": "Advanced",
    #      "subject": "Web Development", "url": "https://www.futurelearn.com/courses/introduction-to-web-development-96"},
    #     {"id": 97, "title": "Introduction to Cybersecurity 97", "platform": "FutureLearn", "difficulty": "Beginner",
    #      "subject": "Cybersecurity", "url": "https://www.futurelearn.com/courses/introduction-to-cybersecurity-97"},
    #     {"id": 98, "title": "Introduction to Mobile Development 98", "platform": "edX", "difficulty": "Advanced",
    #      "subject": "Mobile Development", "url": "https://www.edx.org/course/introduction-to-mobile-development-98"},
    #     {"id": 99, "title": "Introduction to Computer Vision 99", "platform": "edX", "difficulty": "Intermediate",
    #      "subject": "Computer Vision", "url": "https://www.edx.org/course/introduction-to-computer-vision-99"},
    #     {"id": 100, "title": "Introduction to AI 100", "platform": "FutureLearn", "difficulty": "Intermediate",
    #      "subject": "AI", "url": "https://www.futurelearn.com/courses/introduction-to-ai-100"},
    # ]
    #
    # #adding courses to the session:
    # for c in courses:
    #     course = Course(**c)
    #     db.session.add(course)
    #
    # db.session.commit()
