"""empty message

Revision ID: 146723273e2f
Revises: f092bdead889
Create Date: 2025-05-05 15:13:57.820582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146723273e2f'
down_revision = 'f092bdead889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('meeting_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
